In [3]:
fin_leaders_america_path = Path('resources/fin_leaders_america.csv')
investors_leadership_path = Path('resources/invstrs_leadership.csv')
fin_leaders_mem_path = Path('resources/fin_leaders_members.csv')
investors_leadership_mem_path = Path('resources/invstrs_leadership_members.csv')

In [8]:
fin_leaders_america = pd.read_csv(fin_leaders_america_path)
investors_leadership = pd.read_csv(investors_leadership_path)
fin_leaders_mem = pd.read_csv(fin_leaders_mem_path)
investors_leadership_mem = pd.read_csv(investors_leadership_mem_path)

In [13]:
combined_dues = pd.concat(
    [fin_leaders_america, investors_leadership], axis="rows", join="inner"
)
combined_dues

          MemberName  DuesOwed  DuesPaid
0      Warren Buffet         0      2500
1       Janet Yellen       100      2400
2    Abigail Johnson         0      2500
3         Larry Fink      2500         0
0      Warren Buffet         0      2500
1       Janet Yellen       100      2400
2    Abigail Johnson         0      2500
3         Larry Fink      2500         0
4       Mario Draghi      2500         0
5  Michael Bloomberg      2500         0
6          Ray Dalio         0      2500

In [23]:
combined_members = pd.concat(
    [fin_leaders_mem, investors_leadership_mem], axis="rows", join="inner"
)
combined_members

          MemberName MembershipStatus
0      Warren Buffet    Good Standing
1       Janet Yellen    Good Standing
2    Abigail Johnson    Good Standing
3         Larry Fink       Delinquent
0      Warren Buffet    Good Standing
1       Janet Yellen    Good Standing
2    Abigail Johnson    Good Standing
3         Larry Fink       Delinquent
4       Mario Draghi       Delinquent
5  Michael Bloomberg       Delinquent
6          Ray Dalio    Good Standing

In [24]:
dues_member_status = pd.concat(
    [combined_dues, combined_members], axis="columns", join="inner"
)
dues_member_status

InvalidIndexError: Reindexing only valid with uniquely valued Index objects